import title from "process";
import "./globals.css";
export const Metadata = {
  title: 'Next.js',
  description: 'Generated by Next.js',
}


export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body
      >
       {children}
       
      </body>
    </html>
  );
}
